version: '3.8'

networks:
  laravel_react:

services:
  nginx:
    container_name: laravel_react_nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8100:80"
      - "443:443"
    networks:
      - laravel_react
    depends_on:
      - app
    
  app:
    container_name: laravel_react_php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes: 
      - ./:/var/www/html
    networks:
      - laravel_react
    depends_on:
      - mysql

  mysql:
    container_name: laravel_react_mysql
    image: mysql
    tty: true
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: laravel_react
      MYSQL_USER: laravel_react_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel_react

  node:
    container_name: laravel_react_node
    build: ./.docker/node
    tty: true
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_react